CREATE TABLE IF NOT EXISTS MPA_RATE
(
    MPA_RATE_ID     INTEGER PRIMARY KEY AUTO_INCREMENT,
    MPA_NAME        VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME            VARCHAR NOT NULL,
    DESCRIPTION     VARCHAR(200),
    RELEASE_DATE    DATE,
    RATE            INTEGER,
    DURATION        INTEGER,
    MPA_RATE_ID     INTEGER,
    FOREIGN KEY (MPA_RATE_ID) REFERENCES MPA_RATE (MPA_RATE_ID)
);

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID        INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME            VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
    UNIC_ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    FILM_ID         INTEGER,
    GENRE_ID        INTEGER,
    FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (GENRE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USERS
(
    USERS_ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    EMAIL           VARCHAR,
    LOGIN           VARCHAR,
    NAME            VARCHAR,
    BIRTHDAY        DATE
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    UNIC_ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERS_ID         INTEGER,
    FRIEND_ID       INTEGER,
    FOREIGN KEY (USERS_ID) REFERENCES USERS (USERS_ID) ON DELETE CASCADE,
    FOREIGN KEY (FRIEND_ID) references USERS (USERS_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FILM_LIKES
(
    FILM_LIKE_ID    INTEGER PRIMARY KEY AUTO_INCREMENT,
    FILM_ID         INTEGER,
    USERS_ID        INTEGER,
    FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID) ON DELETE CASCADE,
    FOREIGN KEY (USERS_ID) REFERENCES USERS (USERS_ID) ON DELETE CASCADE
)